language: node_js
node_js:
  - "6"

before_script:
  - npm install

script:
  - npm run build

notifications:
  irc:
    channels:
      - "chat.freenode.net#blankon"
    template:
      - "%{repository} (%{commit}) : %{message} %{author}"
      - "Build details: %{build_url}"